### ISSUE TITLE
ktlint ignores .editorcofig

### ISSUE THREAD

**Issue by rozPierog** [cstefFlexin/kotlin-formatter#2]
Hi, thanks for creating a extension that uses ktlint to format files inside VSC. But your current approach (throwing contents of a file into `ktlint`) breaks custom configs that could be found in `.editorconfig` and makes it unusable for certain projects.

I noticed that if you give a path to the file instead of contents of a file as a param ktlint will respect custom rules. I've never worked with VSC extensions, but I'm willing to help you with that if you can provide some pointers on what to edit

**Comment by cstefFlexin** [comment]
👍🏻 Thanks for helping with the project, I'll take a look at your pull request tonight
