### ISSUE TITLE
Obscure error if ktlint cannot autoformat

### ISSUE THREAD

**Issue by rozPierog** [cstefFlexin/kotlin-formatter#3]
If your code has some issues that cannot be autofixed (eg. wildcard-import), this extension will only throw error in notification that also pastes whole contents of a file, that results in unreadable Error.

I would propose somehow parsing it and showing throwing it in `problems` tab or even new terminal

**Comment by cstefFlexin** [comment]
The full error is displayed in the appropriate `output` channel ("Kotlin Formatter"), it may be a good idea to only display the error message on the notification and not the full stack when an error occurs

**Comment by cstefFlexin** [comment]
Just took a look at what's happening, the problem is ktlint returning an non 0 exit code and not returning any formatted code whenever there is something that cannot be autocorrected...

**Comment by rozPierog** [comment]
Looking at sample error log
```
An Error occured when formatting: Command failed: cat <<EOF |ktlint --editorconfig '.editorconfig' --stdin -F
…code…

EOF
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.ReflectionUtil (file:/usr/local/Cellar/ktlint/0.42.1/libexec/ktlint) to field java.lang.Throwable.backtrace
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
<stdin>:66:1: Exceeded max line length (100) (cannot be auto-corrected)
<stdin>:67:2: Exceeded max line length (100) (cannot be auto-corrected)
<stdin>:68:4: Exceeded max line length (100) (cannot be auto-corrected)
```

It would seems sufficient to reduce this log to 

```bash
66:1: Exceeded max line length (100) (cannot be auto-corrected)
67:2: Exceeded max line length (100) (cannot be auto-corrected)
68:4: Exceeded max line length (100) (cannot be auto-corrected)
```

As it contains all the info user needs to understand why formatting failed. My proposal is to just show lines starting in `<stdin>` or show all if non of the lines contain it (as a fallback)
